# Generated by Django 3.2.20 on 2023-07-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'School Card',
                'verbose_name_plural': 'School Cards',
                'db_table': 'school_school_card',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Grade')),
                ('school_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_card.schoolcard', verbose_name='School Card')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'School Card Grade',
                'verbose_name_plural': 'School CardGrades',
                'db_table': 'school_school_card_grade',
            },
        ),
    ]
